apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - repo.yaml
  - deployment.yaml
  - clusterIssuer.yaml
  - issuer.yaml
  - certs.yaml