apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-deployment
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-repo
      sourceRef:
        kind: HelmRepository
        name: cert-manager