apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-deployment
  namespace: cert-manager
spec:
  chart:
      sourceRef:
        kind: OCIRepository
        name: cert-manager-repo
  values:
    crds:
      enabled: true
      keep: false
  interval: 1m0s