apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`jenkins.caffeinatedope.net`)
    kind: Rule
    services:
    - name: jenkins-deployment
      port: 8080
  tls: 
    secretName: wildcard-cert