---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins-operator
  namespace: jenkins
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins-operator/jenkins-operator
      version: '0.8.*'
      sourceRef:
        kind: HelmRepository
        name: jenkins-operator/jenkins-operator
      interval: 5m
  releaseName: jenkins-operator
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m