apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`caffeinatedope.net`)
    kind: Rule
    services:
    - name: httpbin-service
      port: 80
  tls: 
    secretName: central-cert