apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`caffeinatedope.net`)
    kind: Rule
    services:
    - name: httpbin-service
      port: 80
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
    secretName: central-cert # < cert-manager will store the created certificate in this secret.