---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  toolkit.fluxcd.io/tenant: sre-team  
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkinsci
  namespace: jenkins
spec:
  interval: 24h
  url: https://charts.jenkins.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: helmrepo-jenkins 
      version: 5.4.3
  install: 
     disableWait: true
  upgrade:
     disableWait: true
  interval: 30s
  releaseName: jenkins
  targetNamespace: jenkins
  valuesFrom:
    - kind: ConfigMap
      name: jenkins-config
  