apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
resources:
  - deployment.yaml
configMapGenerator:
  - name: jenkins-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
