apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog-ingress
  namespace: blog
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`caffeinatedope.net`) || Host(`www.caffeinatedope.net`)
    kind: Rule
    services:
    - name: blog-service
      port: 4321
  tls: 
    secretName: central-cert